### ISSUE TITLE
Please commit the code

### ISSUE THREAD

**Issue by bennn** [strongscript/strongscript#1]
You should commit the strongscript code! It would make at least one person happy.

**Comment by vanesyan** [comment]
@bennn Hello! The org. and repository itself was reserved for future project in my mind, back in oct. 2016. There's nothing to see here, yet :)

**Comment by bennn** [comment]
Oh! So this isn't [StrongScript](http://plg.uwaterloo.ca/~dynjs/strongscript/)?

**Comment by vanesyan** [comment]
No, it isn't :)

**Comment by vanesyan** [comment]
The author of StrongScript you provided, release his software, it's can be found in the resources section
